### ISSUE TITLE
on kali linux 2018.3 - ModuleNotFoundError in file PhishX.py

### ISSUE THREAD

**Issue by SaurabhKhadtare** [WeebSec/PhishX#12]
![screenshot from 2018-09-20 14-00-35](https://user-images.githubusercontent.com/24351492/45823831-1b34b200-bcde-11e8-9842-25392e625352.png)

**Comment by LulzsecHackz** [comment]
pip3 install pyvirtualdisplay
i had the same problem... it is not written in the install file.

**Comment by V3rB0se** [comment]
`sudo pip install pyvirtualdisplay`

**Comment by sidh1980** [comment]
root@kali:~# python --version
Python 3.6.6
root@kali:~# apt-get update python
E: The update command takes no arguments
root@kali:~# pip install python
Requirement already satisfied: python in /usr/lib/python2.7/lib-dynload
root@kali:~# pip install pyvirtualdisplay
Requirement already satisfied: pyvirtualdisplay in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: EasyProcess in /usr/local/lib/python2.7/dist-packages (from pyvirtualdisplay)
root@kali:~# cd PhishX/
root@kali:~/PhishX# python3 PhishX.py 
Traceback (most recent call last):
  File "PhishX.py", line 43, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'
root@kali:~/PhishX# python3.6 PhishX.py 
Traceback (most recent call last):
  File "PhishX.py", line 43, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'

**Comment by sidh1980** [comment]
![kali-2018-10-10-18-01-29](https://user-images.githubusercontent.com/44024295/46737147-6710c080-ccb8-11e8-81e9-3ec08161bacc.png)

**Comment by Adityahacker** [comment]
bro i have same problem 
plzz how to fix it

**Comment by aimannothman** [comment]
yes bro i have the same problem .. 
can somebody tell me how to fix it??

**Comment by srijaanu** [comment]
![screenshot from 2018-11-10 01-27-42](https://user-images.githubusercontent.com/38577754/48300547-4f8a4a80-e4a5-11e8-8452-40671fea5154.png)

**Comment by srijaanu** [comment]
plz tell me any one for this error

**Comment by uran86** [comment]
This how you solve it:

**sudo pip install pyvirtualdisplay** ( then install **bash installer.sh** again so it get updated into the script )

**Comment by mahbain** [comment]
New,so just trying out

**Comment by ArunDinfinity** [comment]
i had the same problem i solved it by using the following command
im using parrot os
pip install pip
pip install --upgrade pip
pip3 install pyvirtualdisplay
now i get pass this error now im having error at line 44
selenium error :(

**Comment by emsheka** [comment]
anyone knows how to fix this error for pyvirtualdisplay?! :/

**Comment by emsheka** [comment]
Ok Guys. i had same issue and here is the FIX:

1. Update Repositories (if you have allready updated, skip this)
	"apt-get update"
2. Download required Packages by using this command
	"apt-get -y install  gcc make zlib1g-dev"
3. Download Python Package
	"wget https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tgz"

4. Unzip This Package File in the R00T Directory

5 Go Inside Python Folder
	"cd Python-3.6.5"

6. Follow this commands to Install:
	"./configure"
	"make"
	"make install"
7. Now Verify Whether Python is installed or not.
	"which python3"
	"python3 -V"

8. And now, Go To The PhishX Directory
	"cd PhishX"

9. Follow the Commands:
	"sudo bash ./installer.sh"
	"python3 PhishX.py"


Thats All !!
Enjoy.
