### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by MrR3DH3T** [WeebSec/PhishX#35]
python3 PhishX.py
bash """Traceback (most recent call last):
  File "PhishX.py", line 39, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
"""

**Comment by empt1xo** [comment]
LMAO, try installing requests python module use ```pip3 install requests``` command to do so

**Comment by 0verd0se** [comment]
`sudo pip install requests`

**Comment by NetworkAdvisor** [comment]
MadBunnySERVER:/usr/lib/python3.7/dist-packages# sudo pip install requests

Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages
 _______________________________________________________________________
/* When running the last code:  python3 PhishX,py
I get error --- Traceback (most recent call last):
File "PhishX.py", line 39, in
import requests
ModuleNotFoundError: No module named 'requests' -- */
I've checked to see if my pip3 was installed and it says its not, but wont allow me to install it. 
Any feed back on how this may be resolved?

**Comment by Habibizerak** [comment]
Dear all,
i have the below issue while entering python3 phishX.py
(Traceback (most recent call last):
File "PhishX.py", line 39, in
import requests
ModuleNotFoundError: No module named )
kindly help me

**Comment by anonymousx123** [comment]
i am also having the same problem! i have upgraded my linux too. i deleted and downloaded the program 3 times, and its the same. i have tried everything. what is going on? all the commands above didnt work. it says " satisfied " then i run it and BOOM, again the same thing. is it from the program? coz im sure my python is running well. maybe its from the program itself. from the script. coz it says its from the "requests". so it IS from the script. any help please?

**Comment by Habibizerak** [comment]
i think its the problem of firefox because its not redirecting to firefox.
