### ISSUE TITLE
[Help] ImportError: No module named 'pyvirtualdisplay'

### ISSUE THREAD

**Issue by LordRazorXXIV** [WeebSec/PhishX#47]
Hello Sir, how to fix this issue: it keeps saying 
Traceback (most recent call last):
  File "PhishX.py", line 43, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named 'pyvirtualdisplay'

please let me a hand. thank you.

**Comment by jamescv97** [comment]
-You need to update your system : sudo apt-get update and sudo apt-get upgrade
-And try this: sudo python3 Phishx.py 
or try this pip install pyvirtualdisplay and run again the tool.

**Comment by LordRazorXXIV** [comment]
Hello Sir jamescv97

when i was updating my system, an error prompt something like it cannot connect / connection time,

then i change the details of my source.list and pasted this source on it and save it.

deb http://http.kali.org/ /kali main contrib non-free
deb http://http.kali.org/ /wheezy main contrib non-free
deb http://http.kali.org/kali kali-dev main contrib non-free
deb http://http.kali.org/kali kali-dev main/debian-installer
deb-src http://http.kali.org/kali kali-dev main contrib non-free
deb http://http.kali.org/kali kali main contrib non-free
deb http://http.kali.org/kali kali main/debian-installer
deb-src http://http.kali.org/kali kali main contrib non-free
deb http://security.kali.org/kali-security kali/updates main contrib non-free
deb-src http://security.kali.org/kali-security kali/updates main contrib non-free

because the default source.list which is containing: deb http://http.kali.org/kali kali-rolling main non-free contrib

it give me no success but pure error. 

i refer to this link: https://unix.stackexchange.com/questions/429729/apt-get-update-error-in-kali-linux-after-dist-upgrade

**Comment by saikiran994** [comment]
Traceback (most recent call last):
  File "PhishX.py", line 43, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'


actually i updated and upgraded system but still iam getting same error.....

**Comment by bharathmanvas** [comment]
i can solve it
by
first install the python3 by >>sudo apt-get install python3
second install the setuptools by >>pip3 install setuptools
third now install the pyvirtual display by>> pip3 install pyvirtualdisplay

**Comment by ArunDinfinity** [comment]
i solved it using the following
pip install pip
pip install --upgrade pip
sudo pip3 install pyvirtualdisplay
now i reached error line 44 from 43 nice game :(
