### ISSUE TITLE
python3 PhishX.py  Error after all have been installed !! ((File "PhishX.py", line 39, in <module>))

### ISSUE THREAD

**Issue by linux-enthusiastic** [WeebSec/PhishX#68]
Please i have been getting this error whwn i try to run the software -  Need help please.

----------------
kali:~/PhishX# python3 PhishX.py
Traceback (most recent call last):
  File "PhishX.py", line 39, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Kingkhan12398** [comment]
Did u used command "chmod +X PhishX.py" to make it executable?

**Comment by linux-enthusiastic** [comment]
> Did u used command "chmod +X PhishX.py" to make it executable?

I have done all that....yet No luck!!!
